package POJO.XmlModel;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import java.util.Date;

@JacksonXmlRootElement(localName = "record")
public class record {
    @JacksonXmlProperty(localName = "Id")
    public int Id;
    @JacksonXmlProperty(localName = "EntityTypeName")
    public String EntityTypeName;
    @JacksonXmlProperty(localName = "WorkflowItemGuid")
    public String WorkflowItemGuid;
    @JacksonXmlProperty(localName = "StudyId")
    public int StudyId;
    @JacksonXmlProperty(localName = "StudyGuid")
    public String StudyGuid;
    @JacksonXmlProperty(localName = "StudyName")
    public String StudyName;
    @JacksonXmlProperty(localName = "SiteId")
    public int SiteId;
    @JacksonXmlProperty(localName = "SiteGuid")
    public String SiteGuid;
    @JacksonXmlProperty(localName = "SiteCode")
    public String SiteCode;
    @JacksonXmlProperty(localName = "SiteName")
    public String SiteName;
    @JacksonXmlProperty(localName = "SiteCountry")
    public String SiteCountry;
    @JacksonXmlProperty(localName = "PrincipalInvestigatorName")
    public String PrincipalInvestigatorName;
    @JacksonXmlProperty(localName = "SitePrimaryCraName")
    public String SitePrimaryCraName;
    @JacksonXmlProperty(localName = "Name")
    public Object Name;
    @JacksonXmlProperty(localName = "Details")
    public Object Details;
    @JacksonXmlProperty(localName = "Content")
    public Content Content;
    @JacksonXmlProperty(localName = "WorkflowTypeName")
    public String WorkflowTypeName;
    @JacksonXmlProperty(localName = "WorkflowStatusName")
    public String WorkflowStatusName;
    @JacksonXmlProperty(localName = "WorkflowStatusTypeName")
    public String WorkflowStatusTypeName;
    @JacksonXmlProperty(localName = "TargetDate")
    public Date TargetDate;
    @JacksonXmlProperty(localName = "IdentifiedDate")
    public Date IdentifiedDate;
    @JacksonXmlProperty(localName = "IdentifiedPersonName")
    public String IdentifiedPersonName;
    @JacksonXmlProperty(localName = "CreatedDate")
    public Date CreatedDate;
    @JacksonXmlProperty(localName = "CreatedPersonId")
    public int CreatedPersonId;
    @JacksonXmlProperty(localName = "CreatedPersonExternalIdentifier")
    public String CreatedPersonExternalIdentifier;
    @JacksonXmlProperty(localName = "CreatedPersonName")
    public String CreatedPersonName;
    @JacksonXmlProperty(localName = "ModifiedDate")
    public Date ModifiedDate;
    @JacksonXmlProperty(localName = "ModifiedPersonId")
    public int ModifiedPersonId;
    @JacksonXmlProperty(localName = "ModifiedPersonExternalIdentifier")
    public String ModifiedPersonExternalIdentifier;
    @JacksonXmlProperty(localName = "ModifiedPersonName")
    public String ModifiedPersonName;
    @JacksonXmlProperty(localName = "IsPackagedFlag")
    public boolean IsPackagedFlag;
    @JacksonXmlProperty(localName = "SiteVisitId")
    public int SiteVisitId;
    @JacksonXmlProperty(localName = "SiteVisitEventType")
    public String SiteVisitEventType;
    @JacksonXmlProperty(localName = "SiteVisitPrimaryCraName")
    public String SiteVisitPrimaryCraName;
    @JacksonXmlProperty(localName = "SiteVisitStartDate")
    public Date SiteVisitStartDate;
    @JacksonXmlProperty(localName = "SiteVisitEndDate")
    public Date SiteVisitEndDate;
    @JacksonXmlProperty(localName = "SiteVisitStatusName")
    public String SiteVisitStatusName;
    @JacksonXmlProperty(localName = "SiteVisitLength")
    public int SiteVisitLength;
    @JacksonXmlProperty(localName = "ClosedDate")
    public Date ClosedDate;
    @JacksonXmlProperty(localName = "ClosedPerson")
    public String ClosedPerson;
    @JacksonXmlProperty(localName = "SiteVisitEventDisplayName")
    public String SiteVisitEventDisplayName;
}
